### ISSUE TITLE
Idea #1 - When the selfbot claims a point

### ISSUE THREAD

**Issue by latelylk** [ethankrein/Trickcord-Treat-Sniper#1]
Should the script check if it received the point and then print a message to the console saying it did?

Expanding on this, is there interest for the selfbot to send a phrase in the chat such as 'gg' when it claims a point?

**Comment by CosmonautNinja** [comment]
I don't really think there is much need? But it could be useful from time to time.

**Comment by latelylk** [comment]
For now I see no point. I'll close this and come back to it if I ever do decide to follow through with this idea.
