### ISSUE TITLE
how do you get this thing working lol

### ISSUE THREAD

**Issue by imbored10** [ethankrein/Trickcord-Treat-Sniper#12]
im so confused i dont know anything about this coding stuff all what i wanted was a macro so i can get every pet while im afk i copied my token and server id and channel id i put them all in that file (i used notepad++) and then i installed nodejs and when i tried to run HalloweenSniper it just kept closing wtf do i do can u make a small 30 sec video where u do the steps so i can copy them 1 by 1

**Comment by latelylk** [comment]
How are you trying to run the script?

**Comment by ethankrein** [comment]
https://github.com/ethankrein/Trickcord-Treat-Sniper#getting-started

I'll expand that getting started here.

1. Clone this repository
2. Edit the config file (options explained in [#options](#options))
3. Navigate to the directory of the cloned repository
4. Open your shell in that directory
    I'm going to assume you're on windows for this.
    1. Inside the folder containing all of the files, hold shift and click somewhere not on a file
    2. When the context menu comes up, choose "Open PowerShell window here"
5. On first install, run `npm install`
6. Run `node HalloweenSniper.js`

**Comment by latelylk** [comment]
https://github.com/latelylk/Trickcord-Treat-Sniper#getting-started

I'll expand that getting started here.

1. Clone this repository
2. Edit the config file (options explained in [#options](#options))
3. Navigate to the directory of the cloned repository
4. Open your shell in that directory
    I'm going to assume you're on windows for this.
    1. Inside the folder containing all of the files, hold shift and click somewhere not on a file
    2. When the context menu comes up, choose "Open PowerShell window here"
5. On first install, run `npm install`
6. Run `node HalloweenSniper.js`

I'm going to close this issue. If you still require help, feel free to keep responding in this thread.
