### ISSUE TITLE
Discord Token

### ISSUE THREAD

**Issue by NestorTimell** [ethankrein/Trickcord-Treat-Sniper#3]
closed

**Comment by NestorTimell** [comment]
found it, please delete

**Comment by latelylk** [comment]
Was your error that you couldn't find your token?

There is now a wiki page for finding your discord token:

https://github.com/latelylk/Trickcord-Treat-Sniper/wiki/Getting-Your-Discord-Token

**Comment by ethankrein** [comment]
There is now a wiki page for finding your discord token:

https://github.com/ethankrein/Trickcord-Treat-Sniper/wiki/Getting-Your-Discord-Token

**Comment by NestorTimell** [comment]
The problem was solved with finding the correct id for token, server and channel. ...and run it correctly in cmd.
