### ISSUE TITLE
Idea: Make an option to set spam text and not delete.

### ISSUE THREAD

**Issue by CosmonautNinja** [ethankrein/Trickcord-Treat-Sniper#6]

**Comment by latelylk** [comment]
This is already similar to #2 but I'll look into setting whether to delete messages.

**Comment by latelylk** [comment]
Features added in #7.

`config.yaml` now has two additional options:

* `toSpam` which allows the user to provide messages to be spammed

* `deleteSpam` which allows the user to specify whether the spammed messages should be auto-deleted
