### ISSUE TITLE
Idea: Optional Delay for Claim

### ISSUE THREAD

**Issue by NestorTimell** [ethankrein/Trickcord-Treat-Sniper#8]
I would like the bot to have a randomized delay option:
example:
Bot claims a point after 1.4 seconds 
Next time bot claims a point after 0.5 seconds

Also it would be nice to toggle on/off, maybe in an optional bind.

**Comment by latelylk** [comment]
`minWait` and `maxWait` in config.yaml do this exact thing. The bot will randomly choose a number between the minimum and maximum time.

I've updated the README to make this feature more clear.

https://github.com/latelylk/Trickcord-Treat-Sniper#claim-delay

**Comment by ethankrein** [comment]
I've updated the README to make this feature more clear.

https://github.com/ethankrein/Trickcord-Treat-Sniper#claim-delay
